# Generated by Django 5.2.7 on 2025-11-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active_worker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_tasks',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_rejected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('adiestrado', 'Adiestrado'), ('regular', 'Regular'), ('especialista', 'Especialista'), ('admin', 'Administrador'), ('superuser', 'Super Usuario')], default='adiestrado', max_length=20),
        ),
    ]
